"""create table birds

Revision ID: 309eb6ccf85f
Revises: 
Create Date: 2023-10-01 19:59:12.396032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309eb6ccf85f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birds')
    # ### end Alembic commands ###
